import Head from 'next/head'
// import ScreenContainer from '@/ui/ScreenContainer'
import VariableHeading from '../components/typography/VariableHeading'
import { ChevronDownIcon } from '@heroicons/react/24/outline'
import { ChatBubbleBottomCenterTextIcon } from '@heroicons/react/24/solid'


export default function Home() {
  return (
    <>
      <Head>
        <title>Canyon Sykler</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div className="relative w-screen h-[90vh]">

        {/* hero section text */}
        <div className="absolute top-[50%] left-32 translate-y-[-50%] z-[999]">
          <span className="text-md text-white mb-2 block">Klær</span>
          <VariableHeading title="hold deg beskyttet mot været" as="h1" styles="font-black text-7xl uppercase text-white max-w-[700px]"/>

          <p className="text-white max-w-[500px] text-xl py-8 leading-8">Beskyttelse mot fukt og kulde med innebygd pusteevne slik at du ikke overopphetes.
            Våre <span className="uppercase">defend+</span> vanntette regnjakker er for ryttere som søker det beste innen ytelse.
          </p>

          <button className="py-3 px-6 text-md text-black rounded-xl bg-white font-light tracking-wider mr-8">Handle våre regnklær</button>
          <button className="py-3 px-6 text-md text-white rounded-xl bg-transparent border border-white font-light tracking-wider">Les mer</button>
        </div>

        <div className="h-[60vh]">
          <video
            src={"/canyonvideo.mp4"}
            type="video/mp4"
            muted
            autoPlay
            loop
            style={{width: "100vw", height: "90vh"}}
            ></video>
        </div>


        <ChevronDownIcon className="w-10 h-10 text-white absolute left-[50%] bottom-4 translate-x-[-50%] z-[999]"/>
        <div className="absolute right-24 bottom-8 z-[999] translate-x bg-stone-800 p-4 rounded-full">
          <ChatBubbleBottomCenterTextIcon className="w-7 h-7 text-white"/>
        </div>
      </div>


    </>
  )
}
